[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "xpas"
authors = [{name = "Nikolai Romashchenko", email = "nikolay.romashchenko@gmail.com"}]
dynamic = ["version", "description"]